"""actualizacion de rol y usuario

Revision ID: 922326048924
Revises: dc9109eb713d
Create Date: 2025-09-15 15:16:45.403287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '922326048924'
down_revision: Union[str, None] = 'dc9109eb713d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('noticias_ibfk_1'), 'noticias', type_='foreignkey')
    op.drop_column('noticias', 'comentario_id')
    op.alter_column('roles', 'nombre',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.create_unique_constraint(None, 'roles', ['nombre'])
    op.alter_column('usuarios', 'contrasena_usuario',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('usuarios', 'rol_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index(op.f('ix_usuarios_correo_usuario'), 'usuarios', ['correo_usuario'], unique=True)
    op.drop_column('usuarios', 'estado_escritor')
    op.drop_column('usuarios', 'estado_editor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('estado_editor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('estado_escritor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_usuarios_correo_usuario'), table_name='usuarios')
    op.alter_column('usuarios', 'rol_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('usuarios', 'contrasena_usuario',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=60),
               nullable=True)
    op.drop_constraint(None, 'roles', type_='unique')
    op.alter_column('roles', 'nombre',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.add_column('noticias', sa.Column('comentario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('noticias_ibfk_1'), 'noticias', 'comentarios', ['comentario_id'], ['id_comentario'])
    # ### end Alembic commands ###
