"""recuperar contraseña

Revision ID: 710045434184
Revises: ea5f35f1d251
Create Date: 2025-09-22 20:13:40.048624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710045434184'
down_revision: Union[str, None] = 'ea5f35f1d251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_column('usuarios', 'reset_token')
    # ### end Alembic commands ###
